AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  golang with strategy


Globals:
  Function:
    Timeout: 5
    MemorySize: 128

    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  StrategyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName:
        Fn::Sub: "${AWS::StackName}"
      CodeUri: app/
      Handler: bootstrap
      Runtime: go1.x #provided.al2023
      Architectures:
        - x86_64
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StrategyFunction:
    Description: Strategy Lambda Function ARN
    Value: !GetAtt StrategyFunction.Arn
  StrategyFunctionIamRole:
    Description: Implicit IAM Role created for Strategy Lambda
    Value: !GetAtt StrategyFunctionRole.Arn